# Generated by Django 5.2.7 on 2025-10-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("embutido", "Embutido"),
                    ("queso", "Queso"),
                    ("fiambre", "Fiambre"),
                    ("bebida", "Bebida"),
                    ("tablita", "Tablita"),
                    ("panini", "Panini"),
                    ("otros", "Otros"),
                ],
                default="otros",
                max_length=20,
            ),
        ),
    ]
